using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ThinkBot.Entities.BoundLocEntities;
using ThinkBot.Entities.BoundLocEntities.Buildings;
using System.Threading;

namespace ThinkBot.Entities.CharacterEntities
{
    public class Dude
    {
        public Location Location { get; set; }  // Keeps track of the current location of the entity
        public int ID { get; set; }             // Entity ID
        public String Name { get; set; }        // Entity Name
        public int Resources { get; set; }      // amount of resources this dude has
        public int Rest { get; set; }           // amount of rest this dude has
        public bool Visible { get; set; }
        public int MovementSpeed { get; set; }
        public Spawn Spawn { get; set; }


        public Dude(int id, Location location)
        {   // dudes always start in a spawn point as invisible. Name is autogenerated.
            // a Dude needs an ID and a spawnpoint Location
            Name = generateName();
            Location = location;
            Visible = false;
            MovementSpeed = 200;
        }

        private string generateName()
        {   // Generates a new name for the character
            return "frank";
        }

        public void DeSpawnDude()
        {   // sets the character invisible
            Visible = false;
        }

        public void SpawnDude()
        {   // sets the character visible
            Visible = true;
        }

        public void EditSpeed(int amount)
        {   // increases or decreases the movement speed of a Dude. This affects the speed at which MoveTo is looped
            if (MovementSpeed - amount < 1)
            { // there should be at least 1 movement
                MovementSpeed = 1;
            }
            else if (MovementSpeed + amount > 900)
            { // there should be a max of 900 movespeed
                MovementSpeed = 900;
            }
            else
            {
                MovementSpeed = MovementSpeed - amount;
            }
        }

        internal void PerformPriority(List<Building> inGameBuildings)
        {
            if (Rest < 5)
            {
                GoRest(FindClosestRestplace(inGameBuildings));
            }
            else if (Resources > 8)
            {
                DeliverResources(FindClosestWarehouse(inGameBuildings));
            }
            else
            {
                GatherResources(FindClosestResource(inGameBuildings));
            }
        }



        private void GatherResources(ResourceHub resource)
        {
            MoveTo(resource);
            resource.EnterBuilding(this);
            Resources++;
            resource.SubtractResource(1);
            Rest--;
            Thread.Sleep(MovementSpeed * 15);
            resource.LeaveBuilding(this);
        }


        private void DeliverResources(Warehouse warehouse)
        {
            MoveTo(warehouse);
            warehouse.EnterBuilding(this);
            Resources--;
            warehouse.AddResource(1);
            Rest--;
            Thread.Sleep(MovementSpeed * 15);
            warehouse.LeaveBuilding(this);
        }


        private void GoRest(House house)
        {
            MoveTo(house);
            house.EnterBuilding(this);
            Rest += 5;
            Thread.Sleep(MovementSpeed * 15);
            house.LeaveBuilding(this);
        }


        private House FindClosestRestplace(List<Building> inGameBuildings)
        {   // finds out which house is the closest to the character, and returns it.

            House closestHouse = null;
            List<House> houses = new List<House>();

            foreach(Building building in inGameBuildings)
            {
                if((building.GetType()).Equals(typeof(House)))
                {
                    houses.Add((House)building);
                }
            }

            foreach (House house in houses)
            {
                if (closestHouse == null)
                {
                    closestHouse = house;
                }
                else
                {
                    if (closestHouse.Location.IsFurtherThan(Location, house.Location))
                    {
                        closestHouse = house;
                    }
                }
            }

            return closestHouse;
        }

        private ResourceHub FindClosestResource(List<Building> inGameBuildings)
        {
            // finds out which resourcehub is the closest to the character, and returns it.

            ResourceHub closestResource = null;
            List<ResourceHub> resourcehubs = new List<ResourceHub>();

            foreach (Building building in inGameBuildings)
            {
                if ((building.GetType()).Equals(typeof(ResourceHub)))
                {
                    resourcehubs.Add((ResourceHub)building);
                }
            }

            foreach (ResourceHub reHub in resourcehubs)
            {
                if (closestResource == null)
                {
                    closestResource = reHub;
                }
                else
                {
                    if (closestResource.Location.IsFurtherThan(Location, reHub.Location))
                    {
                        closestResource = reHub;
                    }
                }
            }

            return closestResource;
        }

        private Warehouse FindClosestWarehouse(List<Building> inGameBuildings)
        {
            // finds out which warehouse is the closest to the character, and returns it.

            Warehouse closestWarehouse = null;
            List<Warehouse> warehouses = new List<Warehouse>();

            foreach (Building building in inGameBuildings)
            {
                if ((building.GetType()).Equals(typeof(Warehouse)))
                {
                    warehouses.Add((Warehouse)building);
                }
            }

            foreach (Warehouse waho in warehouses)
            {
                if (closestWarehouse == null)
                {
                    closestWarehouse = waho;
                }
                else
                {
                    if (closestWarehouse.Location.IsFurtherThan(Location, waho.Location))
                    {
                        closestWarehouse = waho;
                    }
                }
            }

            return closestWarehouse;
        }

        public void MoveTo(Building building)
        {
            EntityMover.MoveTo(building.Location, Location, MovementSpeed);
        }

        public override string ToString()
        {
            return Name + " R : " + Resources + " Rest : " + Rest + " " + Location.ToString();
        }


    }
}
